### ISSUE TITLE
Songs play in random order: Explore premium

### ISSUE THREAD

**Issue by chellyobserver-coder** [SpotCompiled/SpotveeC#37]
it was literally just working 30 minutes ago. When i try to change a song it tells me Songs play in random order and then gives me the explore premium button. I deleted the app and redownloaded it through ALT Store and it still did the same thing. I restarted my phone, and it did the same thing. I'm confused, it was just working 30 minutes ago now it's telling me to get premium again.

I even tried blocking the premium override, restarting the app and doing it again. I did this again but restarted my phone and the problem persists. 
Any help here?

**Comment by Ijdtm7** [comment]
Can confirm I have the same issue. Probably just needs an update

**Comment by chellyobserver-coder** [comment]
It worked fine for 20 minutes randomly today and now I can't even choose songs form the Queue, I have to listen to the songs in order or skip all the way to the song I want to listen to.

**Comment by yodaluca23** [comment]
Should be fixed in latest release.

https://github.com/SpotCompiled/SpotveeC/releases/tag/v3.4.11

**Comment by brandon-mai** [comment]
The issue is up again in the latest release. I was trying to play a song from Recents tab when suddenly all songs are greyed out.

Config overwrite, reinstall, phone restart - nothing works. Could this be due to a change from Spotify side?

Edit: My bad as I haven't read the common issues doc. It's due to my account using a different region - just use the VPN once every 14 days and it works again.

**Comment by MOJACK66** [comment]
I have he same issue the patch worked for like half a day then went back to not working even a reinstall doesn't fix it which was weird too. Ex. cant play specific, songs not fully random, etc.

**Comment by Dogo69Dog** [comment]
> Edit: My bad as I haven't read the common issues doc. It's due to my account using a different region - just use the VPN once every 14 days and it works again.

is there anything to avoid dong this? Or maybe a implementation that would automatically do this? Im having the issue hwer eit would work one day adn then the next it wouldnt

**Comment by brandon-mai** [comment]
@Dogo69Dog The region issue only occurs every 14 days since that's how long Spotify lets you go abroad. If you have problems every other day, I'm afraid it's not due to the region. You can always try the Overwrite Config method tho.

Regarding the region switching automation, sideloaded Spotify (and even the App Store one IIRC) does not support any shortcut action in the background. I made a shortcut that toggles the VPN and plays a song in Spotify, but it isn't that much faster than just doing it manually.

**Comment by ixmsanto** [comment]
Currently, I'm facing the same issue. In a playlist, I played a song; the next song should be from the playlist, right? But it plays out an irrelevant song.

**Comment by suibianzai** [comment]
> The issue is up again in the latest release. I was trying to play a song from Recents tab when suddenly all songs are greyed out.
> 
> Config overwrite, reinstall, phone restart - nothing works. Could this be due to a change from Spotify side?
> 
> Edit: My bad as I haven't read the common issues doc. It's due to my account using a different region - just use the VPN once every 14 days and it works again.

I finally figured out it's because I didn't change the region of my VPN😅Thank you for the feedback. BTW, where is the common issues doc? I can't find it.

**Comment by brandon-mai** [comment]
> I finally figured out it's because I didn't change the region of my VPN😅Thank you for the feedback. BTW, where is the common issues doc? I can't find it.

It's [here in the main repo](https://github.com/whoeevee/EeveeSpotifyReborn/blob/swift/common_issues.md)
